### ISSUE TITLE
This is pseudo polynomial, not polynomial 

### ISSUE THREAD

**Issue by FishmanL** [frankvegadelgado/P-NP#1]
N is exponential in the length of the problem (since it only takes log n bits to specify n) so an algorithm running in O(n) is exponential in problem length--this sort of algorithmic running time is known as PPT(see, e.g,the knapsack problem algorithm)

**Comment by urizoran** [comment]
If you define A to be the set of integers appearing in triplets in C, you will get N=|A|<=3|C| and the running time will be polynomial. What am I missing?

**Comment by FishmanL** [comment]
N may be bounded by A, but it is bounded exponentially by A--see https://en.m.wikipedia.org/wiki/Pseudo-polynomial_time

**Comment by urizoran** [comment]
You could potentially ignore A all together and construct it from the unique elements appearing in C triplets. In which case, the size of A (which is N) is linear in the length of the input - 3|C|•log|A| >= |A|

**Comment by FishmanL** [comment]
The numeric values of those inputs are still exponential in the size of the input.

**Comment by urizoran** [comment]
How is this different than any graph algorithm iterating over all of the graph vertices?

Those algorithms are exponential because the encoding of the graph is at least the length of the number of vertices, as encoding n vertices requires nlogn bits.

Here, even if you don't encode the values of A, and just give N as input (indeed logn bits), you could iterate over the number of triplets, which is definitely linear, and in particular larger than the value of N

**Comment by FishmanL** [comment]
Because the number of triplets isn't necessarily larger than N?

**Comment by urizoran** [comment]
If you are given an array of integers, and it's size - n, and are required to return the sum of elements in the array, surely the naive algorithm going over all of the array elements is polynomial - since the number of iterations is linear in the size of the array.

Maybe I'm missing some fundamental understand in of the problem definition..

**Comment by urizoran** [comment]
Why does N even matter? Order just elements appearing in triplets. Any natural number in [1..n] that doesn't appear in any triplet can be put wherever in the ordering

**Comment by FishmanL** [comment]
This ppt algorithm would be the equivalent of summing all the integers in an array by adding 1 repeatedly (I. E. Summing (1,2) to 3 by adding 1 once for 1, then twice more for 2) which is polynomial in the values of A but exponential in its length. You correctly note that the naive algorithm avoids this problem.

**Comment by FishmanL** [comment]
N matters because the reduction to XOR 2Sat given in the paper requires N clauses.

**Comment by urizoran** [comment]
You got a point with the 2SAT reduction.
What if I propose a reduction from Betweenness to Beetweenness-Small, where BS only received triplets, without N.
The reduction isomorphs triplets values to numbers in the range [1..k] , where k is the number of different values in triplets.
Then reduce BS to XOR-2SAT using the same reduction as in the paper but start with finding "n" - aka k..

**Comment by frankvegadelgado** [comment]
We receive as input the collection C of distinct triples from A. We reduce to a Boolean formula F in 2CNF such that each pair from the elements inside the triples of C has two clauses and each triple in C has six clauses produced in F. It is trivially to see F is polynomially bounded by C. After that, we find the strong connected components of the implications of F. This is also polynomially bounded by the size of F since 2SAT is in P. Finally, we polynomially iterate through the elements of each strong connected component which contains at most all the literals in F that is also polynomially bounded by F. The whole running time of the algorithm is polynomially bounded by the size of C which is the real input due to is polynomially bounded by F. Therefore, the algorithm has a polynomial running time in relation of the size of the input, that is the definition of P, thus Betweenness is in P.

**Comment by frankvegadelgado** [comment]
Thank you very much @FishmanL . I had the collection C as input in the implementation code but not in the pdf proof. Thanks to you I could improve the theoretical documentation. Thank you very much...
